
[tasks.make-icons]
    dir = "{{ config_root }}/icons"
    run = "magick icon.png -resize 16x16 icon16.png && magick icon.png -resize 48x48 icon48.png && magick icon.png -resize 128x128 icon128.png"
